name: 'banking_analytics'
version: '1.0.0'
config-version: 2

profile: 'jaffle_shop_1'

model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_modules"]

models:
  banking_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
